Update forget command

diff --git a/zsh/functions/remove_last_history_entry b/zsh/functions/remove_last_history_entry
--- a/zsh/functions/remove_last_history_entry
+++ b/zsh/functions/remove_last_history_entry
@@ -1,43 +1,35 @@
 # Remove last line from zsh history
 
 function remove_last_history_entry() {
-    # This sub-function checks if the argument passed is a number.
-    # Thanks to @yabt on stackoverflow for this :).
-    is_int() ( return $(test "$@" -eq "$@" > /dev/null 2>&1); )
+    is_int() { test "$@" -eq "$@" 2>/dev/null; }
 
-    # Set history file's location
-    history_file="${HOME}/.zsh_history"
+    history_file="${HISTFILE:-$HOME/.zsh_history}"
     history_temp_file="${history_file}.tmp"
-    line_cout=$(wc -l $history_file)
 
-    # Check if the user passed a number,
-    # so we can delete x lines from history.
-    lines_to_remove=1
-    if [ $# -eq 0 ]; then
-        # No arguments supplied, so set to one.
-        lines_to_remove=1
-    else
-        # An argument passed. Check if it's a number.
-        if $(is_int "${1}"); then
-            lines_to_remove="$1"
-        else
-            echo "Unknown argument passed. Exiting..."
-            return
-        fi
+    lines_to_remove=${1:-1}
+    if ! is_int "$lines_to_remove"; then
+        echo "Invalid argument. Please provide a number."
+        return 1
     fi
 
-    # Make the number negative, since head -n needs to be negative.
-    lines_to_remove="-${lines_to_remove}"
+    # Write current shell's history to the history file
+    fc -W
 
-    fc -W # write current shell's history to the history file.
+    # Remove last N lines from history file
+    if [ -f "$history_file" ]; then
+        head -n -$lines_to_remove "$history_file" > "$history_temp_file" && mv "$history_temp_file" "$history_file"
+    else
+        echo "History file not found: $history_file"
+        return 1
+    fi
 
-    # Get the files contents minus the last entry(head -n -1 does that)
-    #cat $history_file | head -n -1 &> $history_temp_file
-    #cat $history_file | head -n "${lines_to_remove}" &> $history_temp_file
-    cat $history_file | head -n $(($(wc -l < $history_file) - $lines_to_remove)) &> $history_temp_file
-    mv "$history_temp_file" "$history_file"
+    # Read the modified history file
+    fc -R
 
-    fc -R # read history file.
-    #reload
+    # Remove the last N commands from the current session's history
+    for ((i=0; i<lines_to_remove; i++)); do
+        history -d $((HISTCMD-1))
+    done
+
+    echo "Removed last $lines_to_remove command(s) from history."
 }
-
